# -*- coding: utf-8 -*-
"""Bandits Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4KsGtMUKYZXrRsTQ3FBNpwpNp01pGAm
"""

"""
Multi-Armed Bandit (MAB) Framework in Python
=============================================
This script demonstrates three core algorithms for solving the Multi-Armed
Bandit problem (Exploration vs. Exploitation trade-off):
  1. Epsilon-Greedy
  2. Upper Confidence Bound (UCB1)
  3. Thompson Sampling (Bayesian)

Requirements:
  - numpy
  - matplotlib

Usage:
  Run directly: `python bandit_simulation.py`
"""

import numpy as np
import matplotlib.pyplot as plt


class GaussianBanditEnvironment:
    """Simulates an N-armed bandit environment with Gaussian reward distributions."""

    def __init__(self, k_arms=10, seed=42):
        np.random.seed(seed)
        self.k = k_arms
        # Assign true mean reward for each arm from standard Normal distribution
        self.true_means = np.random.normal(loc=0.0, scale=1.0, size=self.k)
        self.optimal_arm = np.argmax(self.true_means)

    def pull(self, arm_idx):
        """Returns a reward sampled from the chosen arm's distribution."""
        return np.random.normal(loc=self.true_means[arm_idx], scale=1.0)


class EpsilonGreedyAgent:
    def __init__(self, k_arms, epsilon=0.1):
        self.k = k_arms
        self.epsilon = epsilon
        self.counts = np.zeros(self.k)  # Number of times each arm was chosen
        self.q_values = np.zeros(self.k)  # Estimated mean reward for each arm

    def select_action(self):
        # Explore with probability epsilon, otherwise exploit best estimated action
        if np.random.rand() < self.epsilon:
            return np.random.choice(self.k)
        return np.argmax(self.q_values)

    def update(self, action, reward):
        # Incremental average update rule: Q_new = Q_old + (1/N) * (Reward - Q_old)
        self.counts[action] += 1
        self.q_values[action] += (reward - self.q_values[action]) / self.counts[action]


class UCBAgent:
    """Upper Confidence Bound (UCB1) Agent."""

    def __init__(self, k_arms, c=2.0):
        self.k = k_arms
        self.c = c  # Exploration intensity parameter
        self.counts = np.zeros(self.k)
        self.q_values = np.zeros(self.k)
        self.total_steps = 0

    def select_action(self):
        self.total_steps += 1
        # Pull each arm at least once to initialize confidence bounds
        for arm in range(self.k):
            if self.counts[arm] == 0:
                return arm

        # Calculate upper confidence bound for each arm
        variance_bound = np.sqrt((self.c * np.log(self.total_steps)) / self.counts)
        ucb_values = self.q_values + variance_bound
        return np.argmax(ucb_values)

    def update(self, action, reward):
        self.counts[action] += 1
        self.q_values[action] += (reward - self.q_values[action]) / self.counts[action]


class ThompsonSamplingAgent:
    """Thompson Sampling Agent assuming Gaussian rewards with unknown mean and unit variance."""

    def __init__(self, k_arms):
        self.k = k_arms
        # Bayesian prior: Normal(mean=0, variance=1) for each arm
        self.means = np.zeros(self.k)
        self.variances = np.ones(self.k)

    def select_action(self):
        # Sample an estimated mean from the posterior distribution of each arm
        samples = np.random.normal(loc=self.means, scale=np.sqrt(self.variances))
        return np.argmax(samples)

    def update(self, action, reward):
        # Bayesian Gaussian-Gaussian conjugate update for known reward variance (1.0)
        old_var = self.variances[action]
        new_var = 1.0 / ((1.0 / old_var) + 1.0)
        new_mean = new_var * ((self.means[action] / old_var) + reward)

        self.variances[action] = new_var
        self.means[action] = new_mean


def run_experiment(env, agent, steps=2000):
    rewards = np.zeros(steps)
    optimal_choices = np.zeros(steps)

    for step in range(steps):
        action = agent.select_action()
        reward = env.pull(action)
        agent.update(action, reward)

        rewards[step] = reward
        optimal_choices[step] = 1 if action == env.optimal_arm else 0

    return rewards, optimal_choices


def plot_results(results, steps):
    plt.figure(figsize=(12, 5))

    # Plot Average Reward over time
    plt.subplot(1, 2, 1)
    for name, (rewards, _) in results.items():
        cum_avg = np.cumsum(rewards) / (np.arange(steps) + 1)
        plt.plot(cum_avg, label=name)
    plt.xlabel('Steps')
    plt.ylabel('Average Reward')
    plt.title('Performance: Average Reward')
    plt.legend()
    plt.grid(True)

    # Plot Optimal Action Percentage over time
    plt.subplot(1, 2, 2)
    for name, (_, optimal_actions) in results.items():
        cum_optimal = np.cumsum(optimal_actions) / (np.arange(steps) + 1) * 100
        plt.plot(cum_optimal, label=name)
    plt.xlabel('Steps')
    plt.ylabel('% Optimal Action Selected')
    plt.title('Exploration Efficiency')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    K_ARMS = 10
    STEPS = 2000

    # Initialize environment and algorithms
    env = GaussianBanditEnvironment(k_arms=K_ARMS, seed=42)

    agents = {
        "Epsilon-Greedy (ε=0.1)": EpsilonGreedyAgent(k_arms=K_ARMS, epsilon=0.1),
        "UCB1 (c=2.0)": UCBAgent(k_arms=K_ARMS, c=2.0),
        "Thompson Sampling": ThompsonSamplingAgent(k_arms=K_ARMS)
    }

    # Execute simulation loop
    results = {}
    for name, agent in agents.items():
        rewards, optimal_actions = run_experiment(env, agent, steps=STEPS)
        results[name] = (rewards, optimal_actions)

    print("--- Simulation Complete ---")
    for name, (rewards, _) in results.items():
        print(f"{name} -> Final Avg Reward: {np.mean(rewards[-100:]):.3f}")

    # Visualize performance comparison
    plot_results(results, STEPS)