# -*- coding: utf-8 -*-
"""xgboost_customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dcw4vH3fdwyH1E7oD_xgBnj8MPDZT_D
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix, balanced_accuracy_score
from sklearn.metrics import roc_auc_score, make_scorer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# This script performs customer churn prediction using an XGBoost model.
# It includes data preprocessing, feature engineering, model training with hyperparameter tuning,
# and comprehensive model evaluation.
# Dataset: Telco Customer Churn (https://github.com/madmashup/targeted-marketing-predictive-engine/blob/master/telecom_churn.csv)


def check_missing_percent(df):
  """Prints the percentage of missing values for each column in a DataFrame."""
  missing = df.isna().mean() * 100
  missing = missing[missing > 0].sort_values(ascending = False)

  if missing.empty:
    print('No missing values detected')

  else:
    print(f'{missing.round(2).to_string(header=False)}% Missing' )

  return missing


def feature_engineering(df):
    """Applies feature engineering steps to the input DataFrame."""
    df = df.drop(columns=['customerID'])

    # Map gender to numerical values
    df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

    # Map binary categorical features to 0 and 1
    binary_map = {'Yes': 1, 'No': 0, 'No internet service': 0, 'No phone service': 0}
    binary_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
                   'StreamingTV', 'StreamingMovies', 'MultipleLines', 'Partner',
                   'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

    for col in binary_cols:
        df[col] = df[col].map(binary_map)

    # Create tenure buckets
    df['tenure_bucket'] = pd.cut(df['tenure'], bins=[0, 18, 36, 54, 72], labels=[0, 1, 2, 3], include_lowest = True).astype(int)

    # Count active services
    service_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                    'TechSupport', 'StreamingTV', 'StreamingMovies']
    df['services_count'] = df[service_cols].sum(axis=1)

    # Convert 'TotalCharges' to numeric, handle missing values, and create charges ratio
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    df['TotalCharges'] = df['TotalCharges'].fillna(0)

    df['charges_ratio'] = df['TotalCharges'] / (df['MonthlyCharges'] + 1)

    # Identify automatic payment methods
    df['is_autopay'] = df['PaymentMethod'].str.contains('automatic').astype(int)

    return df


def encoder(X_train, X_test):
    """Applies encoding to specified categorical features."""
    # Map Contract column to numerical values
    contract_map = {'Month-to-month': 0, 'One year': 1, 'Two year': 2}
    X_train['Contract'] = X_train['Contract'].map(contract_map)
    X_test['Contract'] = X_test['Contract'].map(contract_map)

    # One-Hot Encode specified columns, fitting only on training data to prevent data leakage
    ohe_columns = ['InternetService', 'PaymentMethod']
    ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first')

    train_ohe = pd.DataFrame(ohe.fit_transform(X_train[ohe_columns]), columns=ohe.get_feature_names_out(ohe_columns),
                             index=X_train.index)
    test_ohe = pd.DataFrame(ohe.transform(X_test[ohe_columns]), columns=ohe.get_feature_names_out(ohe_columns),
                            index=X_test.index)

    # Concatenate OHE features and drop original columns
    X_train = pd.concat([X_train.drop(columns=ohe_columns), train_ohe], axis=1)
    X_test = pd.concat([X_test.drop(columns=ohe_columns), test_ohe], axis=1)

    return X_train, X_test



def train_model(X_train, y_train, scale_pos_weight):
    """Trains an XGBoost classifier with RandomizedSearchCV for hyperparameter tuning."""
    model = xgb.XGBClassifier(
        scale_pos_weight=scale_pos_weight, eval_metric='auc', random_state=42)

    # Define hyperparameter distribution for RandomizedSearchCV
    param_dist = {
        'n_estimators': [100, 200, 300, 500],
        'max_depth': [3, 4, 5, 6, 7],
        'learning_rate': [0.01, 0.05, 0.1, 0.2],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.7, 0.8, 1.0],
        'min_child_weight': [1, 3, 5],
        'gamma': [0,0.1,0.3, 0.5]}

    # Perform randomized search for optimal hyperparameters
    search = RandomizedSearchCV(model, param_distributions = param_dist, n_iter = 50, scoring = 'roc_auc',
                                cv = 4, random_state = 42, n_jobs = -1)

    search.fit(X_train, y_train)
    print(f"Best Parameters: {search.best_params_}")
    print(f"Best Cross-Validation [Training] ROC-AUC: {search.best_score_:.4f}")

    return search.best_estimator_


# Threshold raised from 0.50 to improve precision
def evaluate_model(model, X_test, y_test, threshold = 0.55):
    """Evaluates the model performance and displays classification metrics and a confusion matrix."""
    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = (y_prob > threshold).astype(int)

    print("Classification Report: ")
    print(classification_report(y_test, y_pred))
    print(f"Testing ROC AUC: {roc_auc_score(y_test, y_prob):.4f}")
    print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred):.4f}")

    # Plot confusion matrix for visualization
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Churn', 'Churn'],
                yticklabels=['No Churn', 'Churn'])

    plt.title('Confusion Matrix')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()



if __name__ == '__main__':
  # Load the dataset
  df = pd.read_csv('Customer Churn.csv')

  print('Inital Missing Values:')
  check_missing_percent(df)

  # Apply feature engineering
  df = feature_engineering(df)

  # Separate features (X) and target (y)
  X = df.drop(columns = ['Churn'])
  y = df['Churn']

  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, stratify = y, random_state = 42)

  # Apply encoding to training and testing sets
  X_train, X_test = encoder(X_train, X_test)

  # Verify no new nulls after preprocessing
  print('Final Missing Values:')
  check_missing_percent(df)

  # Calculate scale_pos_weight for handling class imbalance
  churn_counts = y_train.value_counts()
  # Tuned down from original value of 2.76 to reduce false positive rate
  scale_pos_weight_df = 0.75 * churn_counts[0] / churn_counts[1]
  print(f'Scale Pos Weight [Tuned Down]: {scale_pos_weight_df}')

  # Train the model
  model = train_model(X_train, y_train, scale_pos_weight_df)

  # Evaluate the trained model
  print("EVALUATION: ")
  evaluate_model(model, X_test, y_test)